
export const cities = [
    { name: 'Cairo' },
    { name: 'Alexandria' },
    { name: 'Giza' },
    { name: '6th of October City' },
    { name: 'Port Said' },
    { name: 'Suez' },
    { name: 'Luxor' },
    { name: 'Asyut' },
    { name: 'Mansoura' },
    { name: 'Tanta' },
    { name: 'Zagazig' },
    { name: 'Faiyum' },
    { name: 'Ismailia' },
    { name: 'Aswan' },
    { name: 'Minya' },
    { name: 'Hurghada' },
    { name: 'Shubra El-Kheima' },
    { name: 'Qena' },
    { name: 'Sohag' },
    { name: 'Banha' },
]
export const specializations = [
    { name: 'Cardiology' },
    { name: 'Dermatology' },
    { name: 'Pediatrics' },
    { name: 'Orthopedics' },
    { name: 'Neurology' },
    { name: 'Ophthalmology' },
    { name: 'Obstetrics and Gynecology' },
    { name: 'Psychiatry' },
    { name: 'General Surgery' },
    { name: 'Internal Medicine' },
    { name: 'Anesthesiology' },
    { name: 'Radiology' },
    { name: 'Urology' },
    { name: 'Oncology' },
    { name: 'Pulmonology' },
    { name: 'Gastroenterology' },
    { name: 'Endocrinology' },
    { name: 'Nephrology' },
    { name: 'Otolaryngology (ENT)' },
    { name: 'Rheumatology' },
    { name: 'Hematology' },
    { name: 'Allergy and Immunology' },
    { name: 'Infectious Disease' },
    { name: 'Physical Medicine and Rehabilitation' },
    { name: 'Emergency Medicine' },
    { name: 'Pathology' },
    { name: 'Plastic Surgery' },
    { name: 'Thoracic Surgery' },
    { name: 'Vascular Surgery' },
    { name: 'Dentistry' },
  ]

